In [1]:
pip install qrcode

   ---------------------------------------- 0.0/46.2 kB ? eta -:--:--
   ---------------------------------------- 0.0/46.2 kB ? eta -:--:--
   ---------------------------------------- 0.0/46.2 kB ? eta -:--:--
   ---------------------------------------- 46.2/46.2 kB 2.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/58.1 kB ? eta -:--:--
   ----------------------------------- ---- 51.2/58.1 kB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 58.1/58.1 kB 1.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
matrix1=np.array([[1,2,3],[4,5,6]])
print(matrix1)

[[1 2 3]
 [4 5 6]]


In [7]:
q,r=np.linalg.qr(matrix1)
print('\nQ:\n',q)
print('\nR:\n',r)
qr_data=str(q)+ '\n' + str(r)


Q:
 [[-0.24253563 -0.9701425 ]
 [-0.9701425   0.24253563]]

R:
 [[-4.12310563 -5.33578375 -6.54846188]
 [ 0.         -0.72760688 -1.45521375]]


In [9]:
import qrcode
img=qrcode.make(qr_data)
img.save('qr_code.png')
print("QR code generated successfully")

QR code generated successfully


In [11]:
from PIL import Image
from numpy import asarray

In [13]:
img = Image.open(r"qr_code.png")
numpydata = asarray(img)
print(numpydata)

[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]]
